### ISSUE TITLE
Latest RabbitMQ (1.1.1) NuGet throws MissingMethodExceptions

### ISSUE THREAD

**Issue by tiggerite** [houseofcat/RabbitMQ.Dataflows#18]
```
System.MissingMethodException : Method not found: 'System.ArraySegment`1<Byte> HouseofCat.Encryption.IEncryptionProvider.Encrypt(System.ReadOnlyMemory`1<Byte>)'.
   at HouseofCat.RabbitMQ.Publisher.ProcessMessagesAsync(ChannelReader`1 channelReader)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at HouseofCat.RabbitMQ.Publisher.ProcessMessagesAsync(ChannelReader`1 channelReader)
   at HouseofCat.RabbitMQ.Publisher.StartAutoPublishAsync(Func`2 processReceiptAsync)
```

It's strange because I see these in the latest Encryption code, did something go awry with nuget packaging of the Encryption library? 1.1.0 works fine

**Comment by tristan-hyams** [comment]
Ugh yeah, I hate it when this happens. I have patched the libraries to do another bump which is mostly all just dependencies.

I need to make the actions/workflows more intelligent.

Let me know if that solves the issue on your end, everythings been pushed (should be update v1.1.2)

**Comment by tiggerite** [comment]
Sorry for the delay getting back with this, I'm still seeing the issue unfortunately.. I only use HouseofCat.RabbitMQ.Pipelines but that brings in HouseofCat.RabbitMQ 1.1.2. Not really sure what's going on.

**Comment by tristan-hyams** [comment]
I am not sure how it happened this time but I suspect it had to do with a restore package cache issue in Github Actions. I have disabled that during the nuget build pipeline till I can understand more about it. Just means much slower publishing.

It _**should be fixed**_ and I pulled it myself to confirm its updated. Let me know if anything else maybe broken since now I am paranoid.

**Comment by tiggerite** [comment]
Yep that's fixed it 👍🏻
