### ISSUE TITLE
Advanced Pipeline Features / Rework

### ISSUE THREAD

**Issue by theodorzoulias** [houseofcat/RabbitMQ.Dataflows#2]
Hi HouseCat, Theodor again, continuing the [discussion](https://github.com/houseofcat/RabbitMQ.Core/issues/12) from the archived repository. As an example for configuring the `TaskScheduler` option, could be a requirement to impose a specific degree of parallelism to the computations performed by multiple blocks. With the base dataflow library you can achieve this by configuring all related blocks with the same `ConcurrentScheduler` (for example `ConcurrentExclusiveSchedulerPair(TaskScheduler.Default, maxConcurrencyLevel: 10).ConcurrentScheduler`).

**Comment by tristan-hyams** [comment]
I will look into providing that - that will make things get tricky with the Pipeline as is, but I have taken a step back and have decided to create some custom blocks instead. Custom Blocks with Step encapsulation.

This new pipeline type should be an order of magnitude faster and more customizeable.

**Comment by tristan-hyams** [comment]
I have setup some quality of life prerequisites in Reinvent Pipelines project.

**Comment by theodorzoulias** [comment]
How are you going to achieve such great performance improvements? Are you going to stop using TPL Dataflow under the hood?

**Comment by tristan-hyams** [comment]
No, still TPL, but because the way I simplified the usage of TPL, my use case (with RabbitMQ) is capped by the performance of a single RabbitMQ consumer. To gain additional performance, I would have to clone the entire pipeline etc.

But if there was a RabbitMQ "ingress block" feeding to a buffer I can scale those blocks horizontally and add as many as I need. Furthermore, decryption, decompression, and deserialization were extracted to multiple transformblocks that each had a little DoP then output to a buffer that stages ready to use data for the users providing actions, my observable bottlenecks should be removed to be as insignificant.

Right now serialization/deserialization, encryption/decryption and compress/decompression are still very tightly coupled with the RabbitMQ consumer (to make it transparent to end users) but if I could relax that to TPL stage, I believe it will place the bottleneck on supplied business logic as opposed to the pipeline itself.

```
        // Main Flow - PreProcessing
        private readonly BufferBlock<ReceivedData> _inputBuffer;
        private readonly TransformBlock<ReceivedData, TState> _createState;
        private readonly TransformBlock<TState, TState> _decryptBlock;
        private readonly TransformBlock<TState, TState> _decompressBlock;
        private readonly BufferBlock<TState> _readyForProcessing;

        // Main Flow - Supplied Steps
        private readonly TransformBlock<TState, TState>[] _suppliedTransforms;

        // Main Flow - PostProcessing
        private readonly BufferBlock<TState> _postProcessing;
        private readonly TransformBlock<TState, TState> _mainCompress;
        private readonly TransformBlock<TState, TState> _mainEncrypt;
        private readonly Action<TState> _finalization;

        // Park Flow
        private readonly BufferBlock<TState> _parkBuffer;
        private readonly TransformBlock<TState, TState> _parkCompress;
        private readonly TransformBlock<TState, TState> _parkEncrypt;
        private readonly Action<TState> _parkFinalization;
```

**Comment by theodorzoulias** [comment]
That sounds very nice! Unfortunately I can't comment further because my knowledge about the RabbitMQ library is very limited. :-)
