### ISSUE TITLE
Reading Channel returned from IPublisher.GetReceivedBufferReader results in a deadlock

### ISSUE THREAD

**Issue by curtisy1** [houseofcat/RabbitMQ.Dataflows#4]
When instantiating a new RabbitService, ```Publisher.StartAutoPublish()``` gets called unconditionally which in turn calls ```ProcessReceiptsAsync()``` unconditionally.
Since the receiptBuffer is created using ```SingleReader = true```, connecting another reader by calling ```GetReceiptBufferReader()``` and trying to read from the channel results in a deadlock.

This could in some cases be necessary if, suppose, one wants to get all failed messages at once, to log the failed amount or further process them in batches.

The way I see it there's three possible solutions to this:
1. Make ```GetReceiptBufferReader()``` private so only the internal implementation can read the buffer. This still wouldn't fix the actual issue of getting all Receipts at once though
2. Provide a second ways of building a ```Func<IEnumerable<PublishReceipt>, ValueTask> processReceiptAsync``` to handle the case of more configurability
3. Set ```SingleReader = false``` preferably when a config option is set. Not sure what this would imply but it seems to be the most durable solution

For an example implementation, see [this trimmed down example](https://github.com/curtisy1/TestCases)

**Comment by tristan-hyams** [comment]
Sehr schön!

This was correct for the original design but its changed over time being publicly exposed, the RabbitService is a completely optional implementation of `HouseofCat.RabbitMQ` somethings could be improved. You could just utilize a Publisher object directly and create a ChannelPool to share.

However, I fully agree with the 3rd option (without the config implementation for now) as I intend to enhance configurations in the future, making it a solid approach to using my library.

By focusing on user impact you get a quick patch :) Also with this upcoming fix, the following adjustment for those that don't subscribe out of choice or forgetfulness I won't impact their code.

```csharp
_receiptBuffer = Channel.CreateBounded<PublishReceipt>(
    new BoundedChannelOptions(1024)
    {
        SingleWriter = false,
        SingleReader = false,
        FullMode = BoundedChannelFullMode.DropOldest, // never block
    });            
```

**Comment by tristan-hyams** [comment]
Change has been published. Close the issue when you are satisfied.

**Comment by curtisy1** [comment]
In my example project it's still blocking forever. However debugging with a local build of the library, I sometimes get a receipt from the buffer which leads me to believe I have some form of concurrency issue.
Any idea what's possibly wrong with this code?

```
var receipts = new List<PublishReceipt>();
var receiptBuffer = _rabbitService.Publisher.GetReceiptBufferReader().ReadAllAsync().ConfigureAwait(false);
      await foreach (var receipt in receiptBuffer) {
        if (receipt.IsError) {
          receipts.Add(receipt);
        }
      }
```

**Comment by tristan-hyams** [comment]
ReadAllAsync() being called internally to RabbitService with a default behavior, to override what you are doing with a PublishReceipts internally, you need to pull them out.

The ReadAllAsync() is being blocked by the RabbitService itself since we do the exact same thing.

Instead, provide a Func for RabbitService that simply transports the PublishReceipts into a ConcurrentQueue or Channel<PublishReceipt> (for thread safety) that is in your application. Then with your code above, read all async on your channel.

RabbitService -> Publisher -> InternalBuffer

I give you a hook to do something with the InteralBuffer via a Func<>.   

```
                                  InternalBuffer v
So, RabbitService -> Publisher -> ProcessReceipts -> YourFunc -> Your Queue/Channel -> You read your Queue/Channel.
```

If you want the behavior to finish, i.e. not stream out forever (ReadAllAsync is a stream out forever while channel is open), then use while( channel.WaitToReadAsync()) with while(channel.TryRead(out var receipt);

https://github.com/houseofcat/Tesseract/blob/0f842974712c8a5fcf8ee530fbd3ceff89945e12/src/HouseofCat.RabbitMQ/Publisher/Publisher.cs#L246

This is the default behavior when you don't provide said func to RabbitService
https://github.com/houseofcat/Tesseract/blob/0f842974712c8a5fcf8ee530fbd3ceff89945e12/src/HouseofCat.RabbitMQ/Publisher/Publisher.cs#L256

Your version would be just moving failures to to your internal queue instead of retry.

**Comment by curtisy1** [comment]
Thanks for clearing that up. This certainly makes more sense now that I see it

**Comment by tristan-hyams** [comment]
Happy I could help, let me know if you run into any more issues!
